/*
          List all possible conversions between internal types
  This file has been automatically generated by the MegaWave2 kernel using
          /home/mw/megawave2/kernel_obj/lib/obj/ix86/make_type_conv
*/


/* List all output internal type conversion possibilities
   using the following format :
   i1,o11,o12,...,o1n,NULL,i2,o21,...o2p,NULL,...,NULL,NULL
   String i1 contains the first input internal type and strings
   o11,o12,...,o1n all possible output types in the conversion i->o.
*/

static char *mw_type_conv_out[]=

{
  "fimage","cimage","cfimage","ccimage",NULL,
  "cimage","fimage","cfimage","ccimage",NULL,
  "cfimage","fimage","cimage","ccimage",NULL,
  "ccimage","fimage","cimage","cfimage",NULL,
  "curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "polygons","curves","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fcurves","curves","polygons","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fpolygons","curves","polygons","fcurves","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "dcurves","curves","polygons","fcurves","fpolygons","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "curve","curves","polygons","fcurves","fpolygons","dcurves","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "polygon","curves","polygons","fcurves","fpolygons","dcurves","curve","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fcurve","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fpolygon","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "point_curve","point_fcurve","point_dcurve",NULL,
  "point_fcurve","point_curve","point_dcurve",NULL,
  "point_dcurve","point_curve","point_fcurve",NULL,
  "dcurve","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "morpho_line","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fmorpho_line","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "mimage","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "morpho_set","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "morpho_sets","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cmorpho_line","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cfmorpho_line","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cmimage","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cmorpho_sets","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cmorpho_set","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","flists","flist","dlists","dlist",NULL,
  "flists","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flist","dlists","dlist",NULL,
  "flist","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","dlists","dlist",NULL,
  "dlists","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlist",NULL,
  "dlist","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists",NULL,
  NULL
};

/* List all input internal type conversion possibilities
   using the following format :
   o1,i11,i12,...,i1n,NULL,o2,i21,...i2p,NULL,...,NULL,NULL
   String o1 contains the first output internal type and strings
   i11,i12,...,i1n all possible input types in the conversion i->o.
*/

static char *mw_type_conv_in[]=

{
  "fimage","cimage","cfimage","ccimage",NULL,
  "cimage","fimage","cfimage","ccimage",NULL,
  "cfimage","fimage","cimage","ccimage",NULL,
  "ccimage","fimage","cimage","cfimage",NULL,
  "curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "polygons","curves","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fcurves","curves","polygons","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fpolygons","curves","polygons","fcurves","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "dcurves","curves","polygons","fcurves","fpolygons","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "curve","curves","polygons","fcurves","fpolygons","dcurves","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "polygon","curves","polygons","fcurves","fpolygons","dcurves","curve","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fcurve","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fpolygon","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "point_curve","point_fcurve","point_dcurve",NULL,
  "point_fcurve","point_curve","point_dcurve",NULL,
  "point_dcurve","point_curve","point_fcurve",NULL,
  "dcurve","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "morpho_line","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "fmorpho_line","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "mimage","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "morpho_set","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "morpho_sets","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cmorpho_line","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cfmorpho_line","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cmimage","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmorpho_sets","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cmorpho_sets","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_set","flists","flist","dlists","dlist",NULL,
  "cmorpho_set","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","flists","flist","dlists","dlist",NULL,
  "flists","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flist","dlists","dlist",NULL,
  "flist","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","dlists","dlist",NULL,
  "dlists","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlist",NULL,
  "dlist","curves","polygons","fcurves","fpolygons","dcurves","curve","polygon","fcurve","fpolygon","dcurve","morpho_line","fmorpho_line","mimage","morpho_set","morpho_sets","cmorpho_line","cfmorpho_line","cmimage","cmorpho_sets","cmorpho_set","flists","flist","dlists",NULL,
  NULL
};
