/*
 * mfile.c for megawave, section mwplight
 *
 * generate the M-file (source of modified module)
 *
 * author : Jacques Froment <jacques.froment@univ-ubs.fr> (2005-2007)
 * author : Nicolas Limare <nicolas.limare@cmla.ens-cachan.fr> (2008)
 */

/* TODO: move to ANSI-only code */
/* (change call to WriteFuncPrototype() in afile.c and see note
 * in WriteFuncPrototype() */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "mwplight-defs.h"
#include "io.h"

#include "library.h"

#define MSG_ERROR_BODY_NOT_PARSED \
     "C body not parsed !"
#define MSG_ERROR_REOPEN_FILE \
     "Cannot reopen file \"%s\" for reading"
#define MSG_ERROR_OPEN_FILE \
     "Cannot open file \"%s\" for writing"


/*
 * write the header
 */
static void writeMheader(FILE * mfile)
{
     fprintf(mfile, "/*\n");
     fprintf(mfile, " * This M-file has been generated by\n");
     fprintf(mfile, " * the megawave light preprocessor.\n");
     fprintf(mfile, " * It contains the source of the modified module\n");
     fprintf(mfile, " * '%s' (to be archived in library).\n", module_name);
     fprintf(mfile, " */\n\n");

     /*
      * Write linemarker preprocessing directive so that, in case of error
      * during the compilation, the C compiler will write the name of the
      * module file and the line number where the error is, instead of the
      * name and line number of the M-file.
      * Beware:
      * - this may work for gcc compilers only (not checked for others) ;
      * - in order to get the right line number, do not change the source code
      *   after the linemarker.
      * So, do not put comments.
      * Also, when ANSI declaration will be added, this linemarker will have
      * to be adapted (by e.g. adding a new one after the declaration to
      * re-synchronize line numbers following the example of printfslocation()).
      */
     /*
      * FIXME : standard ANSI syntax?
      *
      * fprintf(mfile, "# 1 %s.c\n", module_name);
      */
}

/*
 * write additional text for t_varfunc <f>
 */
static void writeMVarFunc(FILE * mfile, t_varfunc * f)
{
     /*
      * Function declarations (but the main one) are local to the module file
      * (not to be archived in library); therefore the C storage keyword
      * "static" has to be added in front of function declarations.
      */

     /* TODO: use strlen */
     if (ISCI_FUNCDECL(f) && (C->mfunc != f) && (f->v->Cstorage[0] == '\0'))
          fprintf(mfile, "static ");

     /*
      * TODO: in case of the main function declaration, replace it
      * by the content of <protobuf> (K&R and ANSI declarations).
      * See setprotobuf() for more comments.
      */
}


/*
 * write the body
 */
static void writeMbody(FILE * mfile, FILE * sfile)
{
     int l;
     long n;
     t_varfunc * f;

     f = C->varfunc;
     if (f == NULL)
          error(MSG_ERROR_BODY_NOT_PARSED);

     n = 0;

     while ((l = getc(sfile)) != EOF)
     {
          putc(l, mfile);
          n++;
          if (f && (n == ((f->l0) - 1)))
          {
               writeMVarFunc(mfile, f);
               f = f->next;
          }
     }
}


/*
 * generate M-file
 */

void gen_lib_file(FILE * mfile, FILE * sfile)
{
     writeMheader(mfile);
     writeMbody(mfile, sfile);
}
