/*
  File autogenerated by gengetopt version 2.22
  generated with the following command:
  /usr/bin/gengetopt --func-name=mw_cmdline --arg-struct=mw_args_info --no-handle-error --no-handle-help --no-help --no-handle-version --no-version -i main.ggo --file-name=main_cmdline 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "main_cmdline.h"

const char *mw_args_info_purpose = "Parse a megawave module";

const char *mw_args_info_usage = "Usage: mwplight [-s module-source] [output-options]";

const char *mw_args_info_description = "This parser reads the megawave header of a module. It produces:\n* a library file, with a modified version of the module C code for inclusion in \nthe megawave modules library;\n* a main file, with a main() function in C, for the stand-alone module;\n* a documentation file, documenting the module syntax (interface) in TeX;\n* an interface file, describing the module io, to design the interface for some \nexternal code;\n* a name file, containing the name and group of the module.\n\nAuthor: Jacques Froment <jacques.froment@univ-ubs.fr>\n";

const char *mw_args_info_help[] = {
  "Input:",
  "  -s, --source=filename         module source file name  (default=`-')",
  "\nOutputs (optional):",
  "  -l, --library=filename        library code file name",
  "  -e, --exec=filename           executable code file name",
  "  -d, --documentation=filename  documentation file name",
  "  -i, --interface=filename      interface file",
  "  -n, --name=filename           name file name",
  "\nMisc:",
  "  -m, --module-name=name        module name  (default=`unknown')",
  "  -g, --group-name=name         module group name  (default=`unknown')",
  "",
  "  -h, --help                    print help and exit  (default=off)",
  "  -V, --version                 print version and exit  (default=off)",
  "  -D, --debug                   debug flag  (default=off)",
  "\nUse '-' for standard input/output. Default mode is to use stdin for\nthe source file, and no output activated. The output order doesn't\nfollow the options order (in case of multiple output to a single\nfile/pipe).\n\nThis program is part of the megawave framework.\nSee http://megawave.cmla.ens-cachan.fr/ for details.\n(C) 2008 CMLA, ENS Cachan, 94235 Cachan cedex, France.",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
} mw_cmdline_arg_type;

static
void clear_given (struct mw_args_info *args_info);
static
void clear_args (struct mw_args_info *args_info);

static int
mw_cmdline_internal (int argc, char * const *argv, struct mw_args_info *args_info,
                        struct mw_cmdline_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct mw_args_info *args_info)
{
  args_info->source_given = 0 ;
  args_info->library_given = 0 ;
  args_info->exec_given = 0 ;
  args_info->documentation_given = 0 ;
  args_info->interface_given = 0 ;
  args_info->name_given = 0 ;
  args_info->module_name_given = 0 ;
  args_info->group_name_given = 0 ;
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->debug_given = 0 ;
}

static
void clear_args (struct mw_args_info *args_info)
{
  args_info->source_arg = gengetopt_strdup ("-");
  args_info->source_orig = NULL;
  args_info->library_arg = NULL;
  args_info->library_orig = NULL;
  args_info->exec_arg = NULL;
  args_info->exec_orig = NULL;
  args_info->documentation_arg = NULL;
  args_info->documentation_orig = NULL;
  args_info->interface_arg = NULL;
  args_info->interface_orig = NULL;
  args_info->name_arg = NULL;
  args_info->name_orig = NULL;
  args_info->module_name_arg = gengetopt_strdup ("unknown");
  args_info->module_name_orig = NULL;
  args_info->group_name_arg = gengetopt_strdup ("unknown");
  args_info->group_name_orig = NULL;
  args_info->help_flag = 0;
  args_info->version_flag = 0;
  args_info->debug_flag = 0;
  
}

static
void init_args_info(struct mw_args_info *args_info)
{


  args_info->source_help = mw_args_info_help[1] ;
  args_info->library_help = mw_args_info_help[3] ;
  args_info->exec_help = mw_args_info_help[4] ;
  args_info->documentation_help = mw_args_info_help[5] ;
  args_info->interface_help = mw_args_info_help[6] ;
  args_info->name_help = mw_args_info_help[7] ;
  args_info->module_name_help = mw_args_info_help[9] ;
  args_info->group_name_help = mw_args_info_help[10] ;
  args_info->help_help = mw_args_info_help[12] ;
  args_info->version_help = mw_args_info_help[13] ;
  args_info->debug_help = mw_args_info_help[14] ;
  
}

void
mw_cmdline_print_version (void)
{
  printf ("%s %s\n", MW_CMDLINE_PACKAGE, MW_CMDLINE_VERSION);
}

static void print_help_common(void) {
  mw_cmdline_print_version ();

  if (strlen(mw_args_info_purpose) > 0)
    printf("\n%s\n", mw_args_info_purpose);

  if (strlen(mw_args_info_usage) > 0)
    printf("\n%s\n", mw_args_info_usage);

  printf("\n");

  if (strlen(mw_args_info_description) > 0)
    printf("%s\n", mw_args_info_description);
}

void
mw_cmdline_print_help (void)
{
  int i = 0;
  print_help_common();
  while (mw_args_info_help[i])
    printf("%s\n", mw_args_info_help[i++]);
}

void
mw_cmdline_init (struct mw_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
mw_cmdline_params_init(struct mw_cmdline_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct mw_cmdline_params *
mw_cmdline_params_create(void)
{
  struct mw_cmdline_params *params = 
    (struct mw_cmdline_params *)malloc(sizeof(struct mw_cmdline_params));
  mw_cmdline_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
mw_cmdline_release (struct mw_args_info *args_info)
{

  free_string_field (&(args_info->source_arg));
  free_string_field (&(args_info->source_orig));
  free_string_field (&(args_info->library_arg));
  free_string_field (&(args_info->library_orig));
  free_string_field (&(args_info->exec_arg));
  free_string_field (&(args_info->exec_orig));
  free_string_field (&(args_info->documentation_arg));
  free_string_field (&(args_info->documentation_orig));
  free_string_field (&(args_info->interface_arg));
  free_string_field (&(args_info->interface_orig));
  free_string_field (&(args_info->name_arg));
  free_string_field (&(args_info->name_orig));
  free_string_field (&(args_info->module_name_arg));
  free_string_field (&(args_info->module_name_orig));
  free_string_field (&(args_info->group_name_arg));
  free_string_field (&(args_info->group_name_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, char *values[])
{
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
mw_cmdline_dump(FILE *outfile, struct mw_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", MW_CMDLINE_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->source_given)
    write_into_file(outfile, "source", args_info->source_orig, 0);
  if (args_info->library_given)
    write_into_file(outfile, "library", args_info->library_orig, 0);
  if (args_info->exec_given)
    write_into_file(outfile, "exec", args_info->exec_orig, 0);
  if (args_info->documentation_given)
    write_into_file(outfile, "documentation", args_info->documentation_orig, 0);
  if (args_info->interface_given)
    write_into_file(outfile, "interface", args_info->interface_orig, 0);
  if (args_info->name_given)
    write_into_file(outfile, "name", args_info->name_orig, 0);
  if (args_info->module_name_given)
    write_into_file(outfile, "module-name", args_info->module_name_orig, 0);
  if (args_info->group_name_given)
    write_into_file(outfile, "group-name", args_info->group_name_orig, 0);
  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->debug_given)
    write_into_file(outfile, "debug", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
mw_cmdline_file_save(const char *filename, struct mw_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", MW_CMDLINE_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = mw_cmdline_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
mw_cmdline_free (struct mw_args_info *args_info)
{
  mw_cmdline_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
mw_cmdline (int argc, char * const *argv, struct mw_args_info *args_info)
{
  return mw_cmdline2 (argc, argv, args_info, 0, 1, 1);
}

int
mw_cmdline_ext (int argc, char * const *argv, struct mw_args_info *args_info,
                   struct mw_cmdline_params *params)
{
  int result;
  result = mw_cmdline_internal (argc, argv, args_info, params, NULL);

  return result;
}

int
mw_cmdline2 (int argc, char * const *argv, struct mw_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct mw_cmdline_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = mw_cmdline_internal (argc, argv, args_info, &params, NULL);

  return result;
}

int
mw_cmdline_required (struct mw_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see mw_cmdline_params.check_ambiguity
 * @param override @see mw_cmdline_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, char *possible_values[], const char *default_value,
               mw_cmdline_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };


  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
mw_cmdline_internal (int argc, char * const *argv, struct mw_args_info *args_info,
                        struct mw_cmdline_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct mw_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    mw_cmdline_init (args_info);

  mw_cmdline_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "source",	1, NULL, 's' },
        { "library",	1, NULL, 'l' },
        { "exec",	1, NULL, 'e' },
        { "documentation",	1, NULL, 'd' },
        { "interface",	1, NULL, 'i' },
        { "name",	1, NULL, 'n' },
        { "module-name",	1, NULL, 'm' },
        { "group-name",	1, NULL, 'g' },
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "debug",	0, NULL, 'D' },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "s:l:e:d:i:n:m:g:hVD", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 's':	/* module source file name.  */
        
        
          if (update_arg( (void *)&(args_info->source_arg), 
               &(args_info->source_orig), &(args_info->source_given),
              &(local_args_info.source_given), optarg, 0, "-", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "source", 's',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* library code file name.  */
        
        
          if (update_arg( (void *)&(args_info->library_arg), 
               &(args_info->library_orig), &(args_info->library_given),
              &(local_args_info.library_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "library", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* executable code file name.  */
        
        
          if (update_arg( (void *)&(args_info->exec_arg), 
               &(args_info->exec_orig), &(args_info->exec_given),
              &(local_args_info.exec_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "exec", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* documentation file name.  */
        
        
          if (update_arg( (void *)&(args_info->documentation_arg), 
               &(args_info->documentation_orig), &(args_info->documentation_given),
              &(local_args_info.documentation_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "documentation", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* interface file.  */
        
        
          if (update_arg( (void *)&(args_info->interface_arg), 
               &(args_info->interface_orig), &(args_info->interface_given),
              &(local_args_info.interface_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "interface", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* name file name.  */
        
        
          if (update_arg( (void *)&(args_info->name_arg), 
               &(args_info->name_orig), &(args_info->name_given),
              &(local_args_info.name_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "name", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* module name.  */
        
        
          if (update_arg( (void *)&(args_info->module_name_arg), 
               &(args_info->module_name_orig), &(args_info->module_name_given),
              &(local_args_info.module_name_given), optarg, 0, "unknown", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "module-name", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* module group name.  */
        
        
          if (update_arg( (void *)&(args_info->group_name_arg), 
               &(args_info->group_name_orig), &(args_info->group_name_given),
              &(local_args_info.group_name_given), optarg, 0, "unknown", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "group-name", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'h':	/* print help and exit.  */
        
        
          if (update_arg((void *)&(args_info->help_flag), 0, &(args_info->help_given),
              &(local_args_info.help_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "help", 'h',
              additional_error))
            goto failure;
        
          break;
        case 'V':	/* print version and exit.  */
        
        
          if (update_arg((void *)&(args_info->version_flag), 0, &(args_info->version_given),
              &(local_args_info.version_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "version", 'V',
              additional_error))
            goto failure;
        
          break;
        case 'D':	/* debug flag.  */
        
        
          if (update_arg((void *)&(args_info->debug_flag), 0, &(args_info->debug_given),
              &(local_args_info.debug_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "debug", 'D',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", MW_CMDLINE_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  mw_cmdline_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  mw_cmdline_release (&local_args_info);
  return (EXIT_FAILURE);
}
