#!/usr/bin/make -f
#
# common makefile for megawave, documentation targets
#
# author: Nicolas Limare <nicolas.limare@cmla.ens-cachan.fr> (2009)

default :

clean 	: clean-doc
distclean	: distclean-doc

MAN	= $(DOCNAME).$(MANSECTION)
MANHTML	= $(DOCNAME).html

.PHONY	: man
man	: $(MAN) $(MANHTML)


# markdown to manpage
$(MAN) : $(basename $(MAN)).man.mdwn
	-test -x $(PANDOC) && $(PANDOC) $(PANDOC_FLAGS) -t man -o $@ $<

# markdown to html
$(MANHTML) : $(basename $(MAN)).man.mdwn
	-test -x $(PANDOC) && $(PANDOC) $(PANDOC_FLAGS) -t html -o $@ $<


.PHONY	: srcdoc
srcdoc	: html/index.html $(DOCNAME).pdf
	$(MKDIR) $(DOCDIR)/srcdoc/$(DOCNAME)
	$(CP) $(DOCNAME).pdf $(DOCDIR)/srcdoc/
	$(RCP) html/*.html html/*.css html/*.gif html/*.png \
		$(DOCDIR)/srcdoc/$(DOCNAME)/

html/index.html	: doxygen-html.conf $(SRC) $(HDR)
	$(MKDIR) html
	$(DOXYGEN) $<

$(DOCNAME).pdf : latex/refman.tex
	$(MAKE) -C latex refman.pdf
	mv latex/refman.pdf $@

latex/refman.tex	: doxygen-latex.conf $(SRC) $(HDR)
	$(MKDIR) latex
	$(DOXYGEN) $<

doxygen-html.conf	: $(COMMONDIR)/$(DOXYCONF)
	$(CAT) $< > $@
	$(ECHO) -e "\
PROJECT_NAME		= $(DOCNAME)\n\
INPUT			= $(SRCDIR)\n\
STRIP_FROM_PATH		= $(SRCDIR)\n\
GENERATE_HTML		= YES\n\
HTML_OUTPUT		= ./html\n\
HTML_HEADER		= $(COMMONDIR)/doxygen-header.html\n\
HTML_FOOTER		= $(COMMONDIR)/doxygen-footer.html\n\
HTML_STYLESHEET		= $(COMMONDIR)/doxygen.css\n\
#INCLUDE_GRAPH		= YES\n\
#INCLUDED_BY_GRAPH	= YES\n\
#CALL_GRAPH		= YES\n\
#CALLER_GRAPH		= YES\n\
$(DOXY_OVERRIDE)\
" >> $@

doxygen-latex.conf	: $(COMMONDIR)/$(DOXYCONF)
	$(CAT) $< > $@
	$(ECHO) -e "\
PROJECT_NAME		= $(DOCNAME)\n\
INPUT			= $(SRCDIR)\n\
STRIP_FROM_PATH		= $(SRCDIR)\n\
GENERATE_LATEX		= YES\n\
LATEX_OUTPUT		= ./latex\n\
LATEX_HEADER		= $(COMMONDIR)/doxygen-header.tex\n\
$(DOXY_OVERRIDE)\
" >> $@

.PHONY	: clean-doc
clean-doc	:
	$(RM) $(MAN) $(MANHTML)
	$(RRM) html
	$(RRM) latex
	$(RM) $(DOCNAME).pdf
	$(RM) doxygen-html.conf doxygen-latex.conf

.PHONY	: distclean-doc
distclean-doc	: clean-doc
	$(RM) $(MAN) $(MANHTML)
	$(RM) $(DOCDIR)/srcdoc/$(DOCNAME).pdf
	$(RRM) $(DOCDIR)/srcdoc/$(DOCNAME)


