#!/bin/sh 
#--------------------------- Shell MegaWave2 Macro --------------------------#
_sccsid="%Z%MegaWave2 %R%, %M% %I%, %G%";
_Prog="Checkmodules"
_Vers="1.05"
_Date="2002"
_Func="Test system modules"
_Auth="Lionel Moisan";
_Usage="[-help]"
# v 1.03 07/02/02 (JF) : changed test [ $numvar == 0 ] to [ $numvar -eq 0 ]
#----------------------------------------------------------------------------#
# This file is part of the MegaWave2 system macros. 
# MegaWave2 is a "soft-publication" for the scientific community. It has
# been developed for research purposes and it comes without any warranty.
# The last version is available at http://www.cmla.ens-cachan.fr/Cmla/Megawave
# CMLA, Ecole Normale Superieure de Cachan, 61 av. du President Wilson,
#       94235 Cachan cedex, France. Email: megawave@cmla.ens-cachan.fr 
#-----------------------------------------------------------------------------

Incerr()
{
    err=`expr $err + 1`
}

# used for integers
Check_exact()
{
    if [ "$1" != "$2" ]; then Incerr; fi
}

# used for float numbers (threshold at 1% error)
Check_approx()
{
    r=`echo "a=$1;b=$2;c=(a-b)^2;d=0.0001*(a^2+b^2);if (c<=d) 1" | bc 2> /dev/null`
    if [ "$r" != "1" ]; then Incerr; fi
}

# used for random variables (threshold at 10% error)
Check_more_approx()
{
    r=`echo "a=$1;b=$2;c=(a-b)^2;d=0.01*(a^2+b^2);if (c<=d) 1" | bc 2> /dev/null`
    if [ "$r" != "1" ]; then Incerr; fi
}

Pass()
{
    if [ $err -ne 0 ]; then
	echo
	echo "*****" module '<'$1'>' failed
	toterr=`expr $toterr + 1`
	echo $1 >> $tmp/failed
    else
	mwechon "."
    fi
    err=0
    totmod=`expr $totmod + 1`
}

NoPass()
{
    err=0
    totno=`expr $totno + 1`
}

Error()
{
    echo $1
    exit 2
}

Settmpdir()
{
    rmtmproot=0
    if [ ! -d $1 ]; then return 1; fi
    if [ ! -x $1 ]; then return 1; fi
    if [ ! -w $1 ]; then return 1; fi
    tmproot=$1/tmp
    if [ ! -d $tmproot ]; then
	mkdir $tmproot || return 1
	rmtmproot=1
    fi
    if [ -d $tmproot ]; then 
	if [ ! -x $tmproot ]; then return 1; fi
	if [ ! -w $tmproot ]; then return 1; fi
	tmp=$tmproot/checkmodules_tmp
	rm -rf $tmp || return 1
	mkdir $tmp || return 1
    fi
    return 0
}


#----------------------------- MACRO BEGINS HERE -----------------------

#--- Usage
if [ $# -ne 0 ]; then
  . .mw2_help_lg_com
fi

#--- define tmp dir

Settmpdir $MEGAWAVE2 || Settmpdir $MY_MEGAWAVE2 || Error "Cannot set tmp directory. Exit."
rm -f $tmp/failed
touch $tmp/failed

#--- check needed commands

which cut > /dev/null || Error "Command <cut> not found. Exit."


#--- check modules

totmod=0
totno=0
toterr=0 
err=0

echo "---------- Checking system modules ----------"


# common modules (needed for test)

mwechon 'common modules (needed for test): '

fmean cimage > $tmp/1 || Incerr
v=`cut -d"=" -f2 $tmp/1`
Check_approx $v 127.156
Pass fmean

fsize cimage > $tmp/1 || Incerr
v=`cat $tmp/1`
Check_exact "$v" "256 256"
Pass fsize

fnorm -v cimage > $tmp/1 || Incerr
v=`cut -d"=" -f2 $tmp/1`
Check_approx $v 8.73267
Pass fnorm

funzoom -z 4 -o 0 cimage $tmp/1 > /dev/null || Incerr
v=`fnorm -v $tmp/1  | cut -d"=" -f2`
Check_approx $v 16.5741
Pass funzoom

cfunzoom -z 4 -o 0 ccimage $tmp/1 || Incerr
cfgetchannels $tmp/1 $tmp/2 $tmp/3 $tmp/4
fdiff $tmp/2 $tmp/3 $tmp/4 
v=`fnorm -v $tmp/4 | cut -d"=" -f2`
Check_approx $v 12.6513
Pass cfunzoom

cfgetchannels ccimage $tmp/1 $tmp/2 $tmp/3 > /dev/null || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 14.6397
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 17.8047
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 18.248
Pass cfgetchannels

fdiff cimage fimage $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 15.9042
Pass fdiff

cfdiff ccimage cimage $tmp/1 || Incerr
cfgetchannels $tmp/1 $tmp/2 $tmp/3 $tmp/4
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 18.6356
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 21.3019
v=`fnorm -v $tmp/4 | cut -d"=" -f2`
Check_approx $v 21.7275
Pass cfdiff

fadd cimage cimage $tmp/1
fdiff $tmp/1 cimage $tmp/2
v=`fnorm -p 2 -c cimage $tmp/2 | cut -d"=" -f2`
Check_exact $v 0
Pass fadd

fquant cimage $tmp/1 5 > /dev/null || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.42627
Pass fquant

echo "1 5 2 3" | freadasc $tmp/1 2 2 || Incerr
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_approx $v 2.75
v=`fvar $tmp/1 | cut -d"=" -f2`
Check_approx $v 2.91667
Pass freadasc

snorm -v fsignal > $tmp/1 || Incerr
v=`cut -d"=" -f2 $tmp/1`
Check_approx $v 37.827
Pass snorm

ccopy cimage $tmp/1_1
ccopy fimage $tmp/1_2
Mkmovie Cmovie $tmp/1 1 2 || Incerr
v=`grep nimage $tmp/1 | cut -d":" -f2`
Check_exact $v 2
Pass Mkmovie

fconst $tmp/1 10 100 100 || Incerr
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_approx $v 10
Pass fmean

dkinfo curve > $tmp/1 || Incerr
v=`grep "Average step distance" $tmp/1 | cut -d":" -f2`
Check_approx $v 2.04765
Pass dkinfo

echo


# compression/ezwave

mwechon "compression/ezwave: "

cfunzoom -z 4 -o 0 ccimage $tmp/1
cfezw -d -b wave/biortho/htilde/sd09.ir $tmp/1 wave/biortho/h/sd07.ir > /dev/null || Incerr
Pass cfezw

Cfezw $tmp/1 > /dev/null || Incerr
Pass Cfezw

funzoom -z 4 -o 0 cimage $tmp/1
fezw -d -b wave/biortho/htilde/sd09.ir $tmp/1 wave/biortho/h/sd07.ir > /dev/null || Incerr
Pass fezw

Fezw $tmp/1 > /dev/null || Incerr
Pass Fezw

#owave2 -r 5 -e 0 cimage $tmp/1 wave/ortho/da02.ir
#ezw $tmp/1 $tmp/2
NoPass ezw

NoPass fiezw
NoPass iezw
NoPass cfiezw

echo


# compression/lossless

mwechon "compression/lossless: "

funzoom -ftype IMG -z 4 -o 0 cimage $tmp/1 2> /dev/null
arencode2 $tmp/1 $tmp/2 > $tmp/3 || Incerr
v=`grep Rate $tmp/3 | cut -d"=" -f2`
Check_approx $v 7.57324
v=`fsize $tmp/2` 
Check_exact "$v" "3878 1"
Pass arencode2

arencode2 -H $tmp/1 $tmp/2 > /dev/null || Incerr
ardecode2 -r 256 $tmp/2 $tmp/3 > /dev/null || Incerr
Pass ardecode2

cvsencode france.crv > $tmp/1 || Incerr
v=`grep N $tmp/1 | cut -d"=" -f2`
Check_exact $v 7887
v=`grep B $tmp/1 | cut -d"=" -f2`
Check_exact $v 10098
Pass cvsencode

cvsfrecode france.crv > $tmp/1 || Incerr
v=`grep N $tmp/1 | cut -d"=" -f2`
Check_exact $v 7887
v=`grep B $tmp/1 | cut -d"=" -f2`
Check_exact $v 10098
Pass cvsfrecode

cvsorgcode france.crv > $tmp/1 || Incerr
v=`grep N $tmp/1 | cut -d"=" -f2`
Check_exact $v 7887
Pass cvsorgcode

funzoom -ftype IMG -z 4 -o 0 cimage $tmp/1 2> /dev/null
fencode $tmp/1 > $tmp/2 || Incerr
v=`grep brate $tmp/2 | cut -d"=" -f2`
Check_approx $v 7.34399
Pass fencode

echo


# compression/scalar

mwechon "compression/scalar: "

fscalq -p -n 10 cimage $tmp/1 > $tmp/2 || Incerr
v=`cat $tmp/2`
#Check_exact "$v" "..."
v=`fentropy $tmp/1 | cut -d"=" -f2`
Check_approx $v 2.91987
Pass fscalq

fscalq -p -n 10 -o $tmp/2 cimage $tmp/1 > /dev/null || Incerr
fiscalq $tmp/2 $tmp/3 > /dev/null || Incerr
fdiff $tmp/1 $tmp/3 $tmp/2
v=`fnorm -p 2 $tmp/2 | cut -d"=" -f2`
Check_exact $v 0
Pass fiscalq

echo


# compression/vector

mwechon "compression/vector: "

mk_codebook $tmp/1 || Incerr
v=`fsize $tmp/1`
Check_exact "$v" "4 6"
Pass mk_codebook

NoPass fivq
NoPass flbg_adap
NoPass flbg
NoPass flbg_train
NoPass fvq
NoPass mk_trainset

echo


# compression/vqwave

mwechon "compression/vqwave: "

NoPass Cfwivq
NoPass Cfwvq
NoPass Fwivq
NoPass fwivq
NoPass Fwlbg_adap
NoPass fwlbg_adap
NoPass Fwvq
NoPass fwvq
NoPass wlbg_adap

echo


# curve

mwechon "curve: "

area curve > $tmp/1 || Incerr
v=`cut -d"=" -f2 $tmp/1`
Check_exact $v 209718
Pass area

perimeter curve > $tmp/1 || Incerr
v=`cut -d"=" -f2 $tmp/1`
Check_exact $v 8422
Pass perimeter

circle -r 10 -n 100 $tmp/1 || Incerr
v=`area $tmp/1 | cut -d"=" -f2`
Check_approx $v 313.953
v=`perimeter $tmp/1 | cut -d"=" -f2`
Check_approx $v 62.8215
Pass circle

disc $tmp/1 2.5 || Incerr
v=`perimeter $tmp/1 | cut -d"=" -f2`
Check_approx $v 30.5708
Pass disc

dsplit_convex -c . curve $tmp/1 > $tmp/2 || Incerr
v=`cut -d"=" -f2 $tmp/2`
Check_exact $v 1866
Pass dsplit_convex

fsplit_convex -c . curve $tmp/1 > $tmp/2 || Incerr
v=`cut -d"=" -f2 $tmp/2`
Check_exact $v 1866
Pass fsplit_convex

extract_connex cimage $tmp/1 || Incerr
v=`dkinfo $tmp/1 | grep "Number of curves" | cut -d":" -f2`
Check_exact $v 122
Pass extract_connex

fillpoly -x 1100 -y 1100 france.crv $tmp/1 || Incerr
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_approx $v 136.473
Pass fillpoly

echo "10 10 60 20 30 50 e 100 10 110 50 150 20 q" \
| flreadasc 2 $tmp/1 > /dev/null 
fillpolys -x 160 -y 60 $tmp/1 $tmp/1 || Incerr
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_approx $v 201.423
Pass fillpolys

fkbox curve > $tmp/1 || Incerr
v=`grep xmin $tmp/1 | cut -d"=" -f2`
Check_exact $v 63
v=`grep ymin $tmp/1 | cut -d"=" -f2`
Check_exact $v -912
v=`grep xmax $tmp/1 | cut -d"=" -f2`
Check_exact $v 692
v=`grep ymax $tmp/1 | cut -d"=" -f2`
Check_exact $v -123
Pass fkbox

fkcenter curve > $tmp/1 || Incerr
v=`grep xg $tmp/1 | cut -d"=" -f2`
Check_approx $v 336.298
v=`grep yg $tmp/1 | cut -d"=" -f2`
Check_approx $v -467.331
Pass fkcenter

fkcrop 0 -100 700 -200 curve $tmp/1 || Incerr
v=`dkinfo $tmp/1 | grep "Number of curves" | cut -d":" -f2`
Check_exact $v 5
v=`fkcenter $tmp/1 | grep xg | cut -d"=" -f2`
Check_approx $v 324.922
Pass fkcrop

fkzrt curve  $tmp/1 0.5 30 20 20 || Incerr
v=`fkcenter $tmp/1 | grep xg | cut -d"=" -f2`
Check_approx $v 282.455
Pass fkzrt

echo "40 40 60 30 100 100 200 80 80 240 e 240 20 280 20 260 240 200 150 240 40 q" | fkreadasc $tmp/1 > /dev/null
ksplines -j 3 $tmp/1 $tmp/2 || Incerr
v=`dkinfo $tmp/2 | grep "Number of curves" | cut -d":" -f2`
Check_exact $v 2
Pass ksplines

echo "40 40 60 30 100 100 200 80 80 240 q" | fkreadasc $tmp/1 > /dev/null
kspline -j 3 $tmp/1 $tmp/2 || Incerr
v=`perimeter $tmp/2 | cut -d"=" -f2`
Check_approx $v 318.806
Pass kspline

NoPass flconcat
NoPass flscale

echo


# curve/io

mwechon "curve/io: "

echo "10 10 60 20 30 50 e 40 30 41 31 41 20 q" \
| fkreadasc $tmp/1 > /dev/null || Incerr
v=`dkinfo $tmp/1 | grep "Number of curves" | cut -d":" -f2`
Check_exact $v 2
v=`perimeter $tmp/1 | cut -d"=" -f2`
Check_approx $v 93.4166
Pass fkreadasc

echo "10 10 60 20 30 50 e 40 30 41 31 41 20 q" \
| flreadasc 2 $tmp/1 > /dev/null || Incerr
v=`dkinfo $tmp/1 | grep "Number of curves" | cut -d":" -f2`
Check_exact $v 2
v=`perimeter $tmp/1 | cut -d"=" -f2`
Check_approx $v 93.4166
Pass flreadasc

kplot curve $tmp/1 || Incerr
v=`fsize $tmp/1`
Check_exact "$v" "630 790"
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 1.90955
Pass kplot

fkplot -s curve $tmp/1 || Incerr
v=`fsize $tmp/1`
Check_exact "$v" "630 790"
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 1.90955
Pass fkplot

fkprintasc curve > /dev/null || Incerr
v=`fkprintasc curve | wc -l`
Check_exact $v 4115
Pass fkprintasc

flprintasc curve > /dev/null || Incerr
v=`flprintasc curve | wc -l`
Check_exact $v 4115
Pass flprintasc

fkprintfig curve > /dev/null || Incerr
v=`fkprintfig curve | wc -w`
Check_exact $v 8255
Pass fkprintfig

echo "10 10 60 20 30 50 e 40 30 41 31 41 20 q" \
| flreadasc 2 $tmp/1 > /dev/null
fkprintfig $tmp/1 | kreadfig $tmp/2 > /dev/null || Incerr
fkzrt $tmp/2 $tmp/2 0.001 0 0 0
v=`dkinfo $tmp/2 | grep "Number of curves" | cut -d":" -f2`
Check_exact $v 2
v=`area $tmp/2 | cut -d"=" -f2`
Check_exact $v 3600
Pass kreadfig

fkview -o $tmp/1 -n curve || Incerr
v=`fnorm -v $tmp/1 2> /dev/null | cut -d"=" -f2`
Check_approx $v 2.61157
Pass fkview

echo "1 1 6 2 3 5 4 3 4 4 4 2 q" | fkreadasc $tmp/1 > /dev/null
kplotasc $tmp/1 > /dev/null || Incerr
v=`kplotasc $tmp/1 | wc -c`
Check_exact $v 84
Pass kplotasc

echo


# curve/smooth

mwechon "curve/smooth: "

fksmooth -n 20 -s 10 curve $tmp/1 || Incerr
v=`area $tmp/1 | cut -d"=" -f2`
Check_approx $v 204306
v=`perimeter $tmp/1 | cut -d"=" -f2`
Check_approx $v 3128.84
Pass fksmooth

iter_fksmooth -N 2 -n 10 -s 10 curve $tmp/1 || Incerr
v=`dkinfo $tmp/1 | grep "Number of curves" | cut -d":" -f2`
Check_exact $v 3
Pass iter_fksmooth

gass -l 10 curve $tmp/1 || Incerr
v=`area $tmp/1 | cut -d"=" -f2`
Check_approx $v 207081
v=`perimeter $tmp/1 | cut -d"=" -f2`
Check_approx $v 3914.79
Pass gass

iter_gass -N 2 -S 10 curve $tmp/1 || Incerr
v=`dkinfo $tmp/1 | grep "Number of curves" | cut -d":" -f2`
Check_exact $v 3
Pass iter_gass

gcsf -l 10 curve $tmp/1 || Incerr
v=`area $tmp/1 | cut -d"=" -f2`
Check_approx $v 209003
v=`perimeter $tmp/1 | cut -d"=" -f2`
Check_approx $v 3929.08
Pass gcsf

iter_gcsf -N 2 -l 20 curve $tmp/1 || Incerr
v=`dkinfo $tmp/1 | grep "Number of curves" | cut -d":" -f2`
Check_exact $v 3
Pass iter_gcsf

echo


# curve/matching

mwechon "curve/matching: "

NoPass km_bitangents
NoPass km_codecurve_ai
NoPass km_codecurve_si
NoPass km_createdict_ai
NoPass km_createdict_si
NoPass KM_DEMO
NoPass km_flatpoints
NoPass km_inflexionpoints
NoPass km_match_ai
NoPass km_match_si
NoPass km_prematchings
NoPass km_savematchings

echo


# examples

mwechon "examples: "

demohead1 cimage $tmp/1 > /dev/null || Incerr
v=`fsize $tmp/1`
Check_exact "$v" "1 1"
Pass demohead1

demohead2 > /dev/null || Incerr
Pass demohead2

demohead3 cimage $tmp/1 > /dev/null || Incerr
v=`fnorm -p 2 -c cimage $tmp/1 | cut -d"=" -f2`
Check_exact $v 0
Pass demohead3

fadd cimage fimage $tmp/1
fadd1 cimage fimage $tmp/2 || Incerr
v=`fnorm -p 2 -c $tmp/1 $tmp/2 | cut -d"=" -f2`
Check_exact $v 0
Pass fadd1

fadd2 cimage fimage $tmp/2 || Incerr
v=`fnorm -p 2 -c $tmp/1 $tmp/2 | cut -d"=" -f2`
Check_exact $v 0
Pass fadd2

fadd3 cimage fimage $tmp/2 || Incerr
v=`fnorm -p 2 -c $tmp/1 $tmp/2 | cut -d"=" -f2`
Check_exact $v 0
Pass fadd3

fadd4 cimage fimage $tmp/2 || Incerr
v=`fnorm -p 2 -c $tmp/1 $tmp/2 | cut -d"=" -f2`
Check_exact $v 0
Pass fadd4

make_cmovie $tmp/1 || Incerr
v=`fsize $tmp/1_01`
Check_exact "$v" "256 256"
v=`grep nimage $tmp/1 | cut -d":" -f2`
Check_exact $v 20
Pass make_cmovie

make_fmovie $tmp/1 || Incerr
v=`fsize $tmp/1_01`
Check_exact "$v" "256 256"
v=`grep nimage $tmp/1 | cut -d":" -f2`
Check_exact $v 21
Pass make_fmovie

make_ccmovie $tmp/1 || Incerr
ccopy $tmp/1_01 $tmp/2 2> /dev/null
v=`fsize $tmp/2`
Check_exact "$v" "256 256"
v=`grep nimage $tmp/1 | cut -d":" -f2`
Check_exact $v 20
Pass make_ccmovie

make_cfmovie $tmp/1 || Incerr
ccopy $tmp/1_01 $tmp/2 2> /dev/null
v=`fsize $tmp/2`
Check_exact "$v" "256 256"
v=`grep nimage $tmp/1 | cut -d":" -f2`
Check_exact $v 20
Pass make_cfmovie

make_cimage $tmp/1 || Incerr
v=`fsize $tmp/1`
Check_exact "$v" "256 256"
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 0.992188
Pass make_cimage

NoPass view_demo

echo


# image/detection

mwechon "image/detection: "

funzoom -o 0 -z 4 cimage $tmp/1

canny $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 13.5183
Pass canny

align -e 4.3 $tmp/1 $tmp/2 > /dev/null || Incerr
v=`flprintasc $tmp/2 | wc -l`
Check_exact $v 14
Pass align

ll_boundaries -e 11 $tmp/1 $tmp/2 > /dev/null || Incerr
v=`flprintasc $tmp/2 | wc -l`
Check_exact $v 1139
Pass ll_boundaries

ll_edges -e 17 $tmp/1 $tmp/2 > /dev/null || Incerr
v=`flprintasc $tmp/2 | wc -l`
Check_exact $v 526
Pass ll_edges

NoPass harris

echo


# image/domain

mwechon "image/domain: "

fcrop -x 20 -y 20 -o 3 cimage $tmp/1 40 100 50 110 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 3.21633
Pass fcrop

cccrop -x 20 -y 20 -o 3 ccimage $tmp/1 40 100 50 110 2> /dev/null || Incerr
cfgetchannels $tmp/1 $tmp/2 $tmp/3 $tmp/4
fdiff $tmp/3 $tmp/2 $tmp/4
v=`fnorm -v $tmp/4 | cut -d"=" -f2`
Check_approx $v 6.01568
Pass cccrop

cextract cimage $tmp/1 40 100 50 110 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 5.06073
Pass cextract

fextract cimage $tmp/1 40 100 50 110 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 5.06073
Pass fextract

ccextract ccimage $tmp/1 40 100 50 110 || Incerr
cfgetchannels $tmp/1 $tmp/2 $tmp/3 $tmp/4
fdiff $tmp/3 $tmp/2 $tmp/4
v=`fnorm -v $tmp/4 | cut -d"=" -f2`
Check_approx $v 6.9226
Pass ccextract

clocal_zoom -x 100 -y 150 -W 64 -X 3 cimage $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.07492
Pass clocal_zoom

flocal_zoom -x 100 -y 150 -W 64 -X 3 cimage $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.07492
Pass flocal_zoom

cclocal_zoom -x 100 -y 150 -W 64 -X 3 ccimage $tmp/1 || Incerr
cfgetchannels $tmp/1 $tmp/2 $tmp/3 $tmp/4
fdiff $tmp/3 $tmp/2 $tmp/4
v=`fnorm -v $tmp/4 | cut -d"=" -f2`
Check_approx $v 8.50785
Pass cclocal_zoom

funzoom -o 0 -z 4 cimage $tmp/1

czoom -X 4 -o 5 $tmp/1 $tmp/2 2> /dev/null || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 5.97412
Pass czoom

cczoom -X 4 -o 5 $tmp/1 $tmp/2 2> /dev/null || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 5.97412
Pass cczoom

fzoom -X 4 -o 5 $tmp/1 $tmp/2 2> /dev/null || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 5.969
Pass fzoom

csample cimage $tmp/1 4 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 19.2588
Pass csample

fsample cimage $tmp/1 4 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 19.2588
Pass fsample

cextcenter -f 27 cimage $tmp/1 || Incerr
v=`fsize $tmp/1`
Check_exact "$v" "243 243"
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.76071
Pass cextcenter

cfextcenter -ftype IMG -f 27 ccimage $tmp/1 2> /dev/null || Incerr
v=`fsize $tmp/1` 
Check_exact "$v" "243 243"
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 15.6567
Pass cfextcenter

fmaskrot -s 30 -b 10 cimage $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 6.09773
Pass fmaskrot

fproj -x 100 -y 120 -o 3 cimage $tmp/1 10 20 250 40 80 210 130 200 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 9.06184
Pass fproj

fzrt -o 3 cimage $tmp/1 1.1 57 -10 -20 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 7.30864
Pass fzrt

frot -a 35 cimage $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 5.02289
Pass frot

fdirspline cimage 5 $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 6.31651
Pass fdirspline

finvspline cimage 5 $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 41.7204
Pass finvspline

ccopy cimage $tmp/1_1
ccopy fimage $tmp/1_2
Mkmovie Cmovie $tmp/1 1 2

cmzoom -o 3 -X 2 $tmp/1 $tmp/2 2> /dev/null || Incerr
fdiff $tmp/2_01 $tmp/2_02 $tmp/3
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 9.81426
Pass cmzoom

ccmzoom -o 3 -X 2 $tmp/1 $tmp/2 2> /dev/null || Incerr
fdiff $tmp/2_01 $tmp/2_02 $tmp/3
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 9.81426
Pass ccmzoom

cmextract -b 0 $tmp/2 $tmp/3 30 30 1 170 170 1 $tmp/1 50 50 2 || Incerr
fdiff $tmp/3_01 $tmp/3_02 $tmp/4
v=`fnorm -v $tmp/4 | cut -d"=" -f2`
Check_approx $v 8.09011
Pass cmextract

cmparitysep -l $tmp/1 $tmp/2 || Incerr
fdiff $tmp/2_01 $tmp/2_03 $tmp/3
fdiff $tmp/2_02 $tmp/2_04 $tmp/4
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 14.6972
v=`fnorm -v $tmp/4 | cut -d"=" -f2`
Check_approx $v 14.74
Pass cmparitysep

NoPass cmcollect
NoPass ccmcollect

echo


# image/filter

mwechon "image/filter: "

cfunzoom -z 4 -o 0 ccimage $tmp/1
cfdiffuse $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 2> /dev/null | cut -d"=" -f2`
Check_approx $v 9.08767
Pass cfdiffuse

cfmdiffuse -n 2 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2_01 2> /dev/null | cut -d"=" -f2`
Check_approx $v 9.08767
v=`fnorm -v $tmp/2_02 2> /dev/null | cut -d"=" -f2`
Check_approx $v 7.25923
Pass cfmdiffuse

funzoom -z 4 -o 0 -ftype IMG cimage $tmp/1 2> /dev/null

erosion -r 1.5 -n 1 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 13.8314
Pass erosion

opening -r 1.5 -n 1 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 13.77
Pass opening

median -r 1.5 -n 1 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 13.7447
Pass median

amss -l 2 -d $tmp/2 $tmp/1 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 11.838
Pass amss

fquant $tmp/1 $tmp/2 5 > /dev/null
osamss -l 2 $tmp/2 $tmp/3 || Incerr
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 11.8249
Pass osamss

heat -n 10 -s 0.1 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 10.777
Pass heat

fsmooth -S 2 -W 1 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 6.23447
Pass fsmooth

echo "-1 1 -1 1" | freadasc $tmp/2 2 2
fconvol $tmp/1 $tmp/2 $tmp/3 || Incerr
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 26.6814
Pass fconvol

fsepconvol -g 2 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 9.13969
Pass fsepconvol

fgrain -a 20 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 13.8573
Pass fgrain

forder -e 5 -n 1 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 13.697
Pass forder

fsharpen -p 50 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 22.7716
Pass fsharpen

NoPass cfsharpen 

rotaffin -r 5 -a 3 -t 3 -T 0 -A 5 $tmp/2 || Incerr
v=`grep nimage $tmp/2 | cut -d":" -f2`
Check_exact $v 15
v=`fnorm -v $tmp/2_10 | cut -d"=" -f2`
Check_approx $v 29.1366
Pass rotaffin

infsup -n 2 $tmp/1 $tmp/2 $tmp/3 || Incerr
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 11.2894
Pass infsup

ll_sharp -p 20 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 16.9317
Pass ll_sharp

resthline $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 16.5496
Pass resthline

shock -n 10 -s 0.1 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 19.0514
Pass shock

tvdenoise $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 14.5187
Pass tvdenoise

cmextract cmovie $tmp/1 128 128 3 140 140 7
mam -n 20 -a 0 $tmp/1 $tmp/2 > /dev/null || Incerr
v=`fnorm -v $tmp/2_03 | cut -d"=" -f2`
Check_approx $v 8.49737
Pass mam

prolate -n 128 3 0.5 $tmp/1 > /dev/null || Incerr
v=`fsize $tmp/1` 
Check_exact "$v" "3 3"
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_approx $v 0.111111
Pass prolate

echo


# image/fourier

mwechon "image/fourier: "

fft2d -A $tmp/1 -B $tmp/2 cimage  || Incerr
fextract $tmp/1 $tmp/1 20 20 230 230
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 1234.21
fextract $tmp/2 $tmp/2 20 20 230 230
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 1230.29
Pass fft2d

fft2dpol -M $tmp/1 -P $tmp/2 cimage  || Incerr
fextract $tmp/1 $tmp/1 20 20 230 230
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 784.174
fextract $tmp/2 $tmp/2 20 20 230 230
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 1.65156
Pass fft2dpol

fft2drad -l -s 100 cimage $tmp/1 || Incerr
v=`snorm -b 5 -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 0.0241473
v=`snorm -b 5 -p 2 $tmp/1 | cut -d"=" -f2`
Check_approx $v 3.48635
Pass fft2drad

fft2dview -t 0 -o $tmp/1 cimage || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 2.04972
Pass fft2dview

fftgrad -n $tmp/1 cimage || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.00567
Pass fftgrad

fftrot -a 33 cimage $tmp/1  || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 9.72568
Pass fftrot

funzoom -z 4 -o 0 cimage $tmp/1
fftzoom -z 2 $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 10.8767
Pass fftzoom

fhamming cimage $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 2.74239
Pass fhamming

frandphase fimage $tmp/1 || Incerr
fft2dpol -P $tmp/2 $tmp/1
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_more_approx $v 1.63
Pass frandphase

fextract cimage $tmp/1 10 10 200 200 
fshrink2 $tmp/1 $tmp/1 || Incerr
v=`fsize $tmp/1` 
Check_exact "$v" "128 128"
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.33146
Pass fshrink2

fsym2 $tmp/1 $tmp/1 || Incerr
v=`fsize $tmp/1` 
Check_exact "$v" "256 256"
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.36696
Pass fsym2

wiener -w 10 -g 1 cimage $tmp/1 || Incerr
v=`fnorm -b 10 -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 11.1962
Pass wiener

echo


# image/io

mwechon "image/io: "

ccopy cimage $tmp/1 || Incerr
fdiff cimage $tmp/1 $tmp/1
v=`fnorm -p 2 $tmp/1 | cut -d"=" -f2`
Check_exact $v 0
Pass ccopy

fcopy fimage $tmp/1 || Incerr
fdiff fimage $tmp/1 $tmp/1
v=`fnorm -p 2 $tmp/1 | cut -d"=" -f2`
Check_exact $v 0
Pass fcopy

cccopy ccimage $tmp/1 || Incerr
cfdiff ccimage $tmp/1 $tmp/1
cfgetchannels $tmp/1 $tmp/2 $tmp/3 $tmp/4
v=`fnorm -p 2 $tmp/2 | cut -d"=" -f2`
Check_exact $v 0
v=`fnorm -p 2 $tmp/3 | cut -d"=" -f2`
Check_exact $v 0
v=`fnorm -p 2 $tmp/4 | cut -d"=" -f2`
Check_exact $v 0
Pass cccopy

NoPass cview
NoPass fview
NoPass ccview
NoPass cmview
NoPass ccmview

fconst $tmp/1 0 60 20
echo "hi guys..." | ccputstring -r 3 -c 900 -C 90 $tmp/1 10 1 $tmp/1 || Incerr
ccopy $tmp/1 $tmp/1 2> /dev/null
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 19.8406
Pass ccputstring

cfgetchannels ccimage $tmp/1 $tmp/2 $tmp/3
cfputchannels $tmp/1 $tmp/2 $tmp/3 $tmp/4 || Incerr
cfdiff -ftype IMG ccimage $tmp/4 $tmp/1 2> /dev/null
v=`fnorm -p 2 $tmp/1 | cut -d"=" -f2`
Check_exact $v 0
Pass cfputchannels

cfchgchannels ccimage $tmp/1 || Incerr
cfgetchannels $tmp/1 $tmp/2 $tmp/3 $tmp/4
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 7.36361
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 15.9369
v=`fnorm -v $tmp/4 | cut -d"=" -f2`
Check_approx $v 9.98046
Pass cfchgchannels

cline_extract cimage $tmp/1 30 || Incerr
v=`snorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 11.1133
Pass cline_extract

fline_extract cimage $tmp/1 30 || Incerr
v=`snorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 11.1133
Pass fline_extract

echo "1 5 2 3" | creadasc $tmp/1 2 2 || Incerr
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_approx $v 2.75
v=`fvar $tmp/1 | cut -d"=" -f2`
Check_approx $v 2.91667
Pass creadasc

cprintasc $tmp/1 > $tmp/2 || Incerr
v=`cat $tmp/2 | wc -l`
Check_exact $v 1
Pass cprintasc

fprintasc $tmp/1 > $tmp/2 || Incerr
v=`cat $tmp/2 | wc -l`
Check_exact $v 1
Pass fprintasc

echo


# image/level_lines

mwechon "image/level_lines: "

Pass flst
Pass flst_pixels
Pass flst_reconstruct
Pass flst_boundary

Pass flst_bilinear
Pass flstb_boundary
Pass flstb_dual
Pass flstb_dualchain
Pass flstb_quantize
Pass flstb_tv

Pass fml_ml
Pass fsaddles
Pass ll_distance
Pass ll_extract
Pass llmap
Pass ll_remove
Pass llremove
Pass llview

Pass ml_decompose
Pass ml_draw
Pass ml_extract
Pass ml_fml
Pass ml_reconstruct

Pass mscarea
Pass tjmap
Pass tjpoint

echo


# image/misc

mwechon "image/misc: "

cdisc $tmp/1 100 100 || Incerr
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_approx $v 126.888
Pass cdisc

funzoom -z 4 -o 0 -ftype IMG cimage $tmp/1 2> /dev/null
cdisc -r 16 $tmp/2 64 64
binarize -i $tmp/2 $tmp/2
fmask $tmp/3 $tmp/2 $tmp/2 $tmp/1
fmask -i -c 1 $tmp/2 $tmp/2 $tmp/2 
disocclusion $tmp/3 $tmp/2 $tmp/4 > $tmp/1 || Incerr
v=`grep energy $tmp/1 | cut -d"=" -f2`
#Check_approx $v 980.02
v=`fnorm -v $tmp/4 | cut -d"=" -f2`
#Check_approx $v 14.66
Pass disocclusion

NoPass drawocclusion

echo "10 10 60 20 30 50 e 100 10 110 50 150 20 q" \
| flreadasc 2 $tmp/1 > /dev/null 
fillpolys -x 160 -y 60 $tmp/1 $tmp/1 
emptypoly $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 12.4411
Pass emptypoly

binarize -i -t 120 cimage $tmp/1
thinning $tmp/1 $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 17.7433
Pass thinning

funzoom -z 4 -o 0 -ftype IMG cimage $tmp/1 2> /dev/null
binarize -i -t 120 $tmp/1 $tmp/1
skeleton -n 10 $tmp/1 seg_mask $tmp/2 > /dev/null || Incerr
v=`grep nimage $tmp/2 | cut -d":" -f2`
Check_exact $v 11
v=`fnorm -v $tmp/2_11 | cut -d"=" -f2`
Check_approx $v 32.5981
Pass skeleton

NoPass lsnakes
NoPass lsnakes_demo
NoPass mac_snakes

echo


# image/operations

mwechon "image/operations: "

faxpb -a 2 -b 10 cimage $tmp/1 || Incerr
faxpb -a 0.5 -b -5 $tmp/1 $tmp/2 || Incerr
fdiff $tmp/2 cimage $tmp/3
v=`fnorm -p 2 $tmp/3 | cut -d"=" -f2`
Check_exact $v 0
Pass faxpb

#fop -m -A cimage cimage $tmp/1 || Incerr
#v=`fnorm -p 2 $tmp/1 | cut -d"=" -f2`
#Check_exact $v 0
NoPass fop

faxpb -a -1 cimage $tmp/1
fabso $tmp/1 $tmp/2
fdiff $tmp/2 cimage $tmp/3
v=`fnorm -p 2 $tmp/3 | cut -d"=" -f2`
Check_exact $v 0
Pass fabso

fentropy cimage > $tmp/1 || Incerr
v=`cat $tmp/1 | cut -d"=" -f2`
Check_approx $v 7.51668
Pass fentropy

fconst $tmp/1 0 10 10
fpset $tmp/1 5 5 100 $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 2
Pass fpset

fderiv -n $tmp/1 cimage || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 3.85916
Pass fderiv

finfo cimage > $tmp/1 || Incerr
v=`grep "bv norm" $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.732667
Pass finfo

fmse -n cimage fimage > $tmp/1 || Incerr
v=`grep "^SNR" $tmp/1 | cut -d"=" -f2`
Check_approx $v -3.48774
v=`grep PSNR $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.10192
v=`grep MSE $tmp/1 | cut -d"=" -f2`
Check_approx $v 2.23241
v=`grep MRD $tmp/1 | cut -d"=" -f2`
Check_approx $v 89.7111
Pass fmse

cdisc $tmp/1 256 256
fmask $tmp/2 $tmp/1 cimage fimage || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 11.5658
Pass fmask

fpsnr255 fimage > $tmp/1 || Incerr
v=`cat $tmp/1 | cut -d"=" -f2`
Check_approx $v 0.347482
Pass fpsnr255

frthre -l 100 cimage $tmp/1 || Incerr
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_approx $v 44.9395
Pass frthre

echo


# image/seg

mwechon "image/seg: "

Pass one_levelset
Pass segct
Pass msegct
Pass mschannel
Pass segtxt

echo


# image/shape_recognition

mwechon "image/shape_recognition: "

Pass CLEAR_BASE
Pass PUT_TO_BASE
Pass READ_BASE
Pass RECOGNIZE
Pass SR_DEMO
Pass sr_distance
Pass sr_genhypo
Pass sr_normalize
Pass sr_signature

echo


# image/values

mwechon "image/values: "

binarize -t 150 cimage $tmp/1 || Incerr
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_approx $v 77.9132
Pass binarize

funzoom -z 8 cimage $tmp/1
fquant $tmp/1 $tmp/1 5 > $tmp/2
v=`cut -d"=" -f2 $tmp/2`
amle_init $tmp/1 $v $tmp/2 || Incerr
v=`fnorm -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 48.7051
Pass amle_init

amle $tmp/2 $tmp/3 2> /dev/null || Incerr
v=`fnorm -v $tmp/3 | cut -d"=" -f2`
Check_approx $v 17.4285
Pass amle

cmextract cmovie $tmp/1 40 170 3 80 210 7
for v in 1 2 3 4 5; do
faxpb -ftype IMG -a 0.1 $tmp/1_0$v $tmp/1_0$v 2> /dev/null
faxpb -ftype IMG -a 10 -b 5 $tmp/1_0$v $tmp/1_0$v 2> /dev/null
done
amle3d_init $tmp/1 10 $tmp/2 || Incerr
v=`fnorm -v $tmp/2_03 | cut -d"=" -f2`
Check_approx $v  26.1018
Pass amle3d_init

amle3d $tmp/2 $tmp/3 || Incerr
v=`fnorm -v $tmp/3_03 | cut -d"=" -f2`
Check_approx $v 4.03325
Pass amle3d

fvalues -r $tmp/1 cimage $tmp/2 || Incerr
v=`grep size $tmp/2 | cut -d":" -f2`
Check_approx $v 256
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 8.73267
Pass fvalues

ccontrast cimage $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 12.5844
Pass ccontrast

ccontrast_local -d 2 cimage $tmp/1 || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 13.2157
Pass ccontrast_local

Pass cfquant
Pass chisto
Pass fhisto
Pass fthre

fconst $tmp/1 0 100 100
cnoise -i 50 $tmp/1 $tmp/1 || Incerr
v=`fmean $tmp/1 | cut -d"=" -f2`
Check_more_approx $v 64
Pass cnoise

fconst $tmp/1 0 100 100
fnoise -g 10 $tmp/1 $tmp/1 || Incerr
v=`fvar $tmp/1 | cut -d"=" -f2`
Check_more_approx $v 100
Pass fnoise

cmextract cmovie $tmp/1 10 10 1 210 210 10
cmnoise -i 50 $tmp/1 $tmp/2
v=`grep nimage $tmp/2 | cut -d":" -f2`
Check_exact $v 10
v=`fmean $tmp/2_05 | cut -d"=" -f2`
Check_more_approx $v 116
Pass cmnoise

NoPass fcontrast
NoPass frank
NoPass flgamma
NoPass bicontrast

echo


# signal

mwechon "signal: "

entropy fsignal > $tmp/1 || Incerr
v=`cut -d"=" -f2 $tmp/1`
Check_approx $v 11.0934
Pass entropy

sshrink2 fsignal $tmp/1 || Incerr
v=`grep "size:" $tmp/1 | cut -d":" -f2`
Check_exact $v 2048
Pass sshrink2

fct1d $tmp/1 $tmp/2 || Incerr
v=`snorm -b 20 -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 3636.57
Pass fct1d

fft1d -A $tmp/2 $tmp/1 || Incerr
v=`snorm -b 20 -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 1888.35
Pass fft1d

sconst -s 256 -a 0.1 $tmp/1 || Incerr
v=`grep "size:" $tmp/1 | cut -d":" -f2`
Check_exact $v 256
v=`snorm -b 20 -v $tmp/1 | cut -d"=" -f2`
Check_exact $v 0
Pass sconst

sderiv fsignal $tmp/1 || Incerr
v=`snorm -b 20 -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 42.9396
Pass sderiv

sdirac -s 100 -a 100 $tmp/1 || Incerr
v=`snorm -b 0 -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 2
v=`snorm -b 0 -p 2 $tmp/1 | cut -d"=" -f2`
Check_approx $v 10
Pass sdirac

sgauss -s 20 $tmp/1 3 || lls
v=`snorm -b 0 -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 0.0130369
v=`snorm -b 0 -p 2 $tmp/1 | cut -d"=" -f2`
Check_approx $v 0.0686237
Pass sgauss

sintegral $tmp/1 $tmp/2 || Incerr
v=`snorm -b 0 -v $tmp/2 | cut -d"=" -f2`
Check_approx $v 0.05
Pass sintegral

sderiv $tmp/1 $tmp/2
smse -n $tmp/1 $tmp/2 > $tmp/3 || Incerr
v=`grep "^SNR" $tmp/3 | cut -d"=" -f2`
Check_approx $v -1.9738
v=`grep PSNR $tmp/3 | cut -d"=" -f2`
Check_approx $v 6.66453
v=`grep MSE $tmp/3 | cut -d"=" -f2`
Check_approx $v 1.57536
v=`grep MRD $tmp/3 | cut -d"=" -f2`
Check_approx $v 70.6568
NoPass smse

sconst -s 1000 -a 0 $tmp/1
snoise -g 1 $tmp/1 $tmp/2 || Incerr
v=`snorm -p 2 $tmp/2 | cut -d"=" -f2`
Check_more_approx $v 1
Pass snoise

#sop -A fsignal -d fsignal $tmp/1 || Incerr
#sop -a 1 -m $tmp/1 $tmp/2 || Incerr
#v=`snorm -p 2 $tmp/2 | cut -d"=" -f2`
#Check_exact $v 0
NoPass sop

splot -ftype RIM -o $tmp/1 -n fsignal 2> /dev/null || Incerr
v=`fnorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 15.6218
Pass splot

echo "0 2 3 4 5 4 3 2 3 4 5 4 3 2 1 0" | sreadasc $tmp/1 16 || Incerr
v=`snorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 1
Pass sreadasc

ssinus -s 100 -a 1 -d 1 $tmp/1  || Incerr
v=`snorm -v $tmp/1 | cut -d"=" -f2`
Check_approx $v 0.0785888
Pass ssinus

NoPass stvrestore
NoPass Swtvdenoise
NoPass w1threshold
NoPass sinfo
NoPass sprintasc
NoPass saxpb

echo


# wave

mwechon "wave: "

owave1 -e 0 fsignal $tmp/1 wave/ortho/da02.ir || Incerr
v=`grep size $tmp/1_01_A.wtrans1d | cut -d":" -f2`
Check_exact $v 1104
v=`grep size $tmp/1_01_D.wtrans1d | cut -d":" -f2`
Check_exact $v 1104
Pass owave1

iowave1 -e 0 $tmp/1 $tmp/2 wave/ortho/da02.ir || Incerr
v=`snorm -t 0.001 -b 2 -p 2 -c fsignal $tmp/2 | cut -d"=" -f2`
Check_exact $v 0
Pass iowave1

biowave1 fsignal $tmp/1 wave/biortho/h/sp02.ir wave/biortho/htilde/sl05.ir || Incerr
v=`grep size $tmp/1_01_A.wtrans1d | cut -d":" -f2`
Check_exact $v 1104
v=`grep size $tmp/1_01_D.wtrans1d | cut -d":" -f2`
Check_exact $v 1104
Pass biowave1

ibiowave1 -e 0 $tmp/1 $tmp/2 wave/biortho/h/sp02.ir wave/biortho/htilde/sl05.ir || Incerr
v=`snorm -t 0.001 -b 2 -p 2 -c fsignal $tmp/2 | cut -d"=" -f2`
Check_exact $v 0
Pass iowave1

NoPass biowave2
NoPass dybiowave2
NoPass dyowave2
NoPass ibiowave2
NoPass iowave2
NoPass owave2
NoPass owtrans_fimage
NoPass precond1d
NoPass precond2d
NoPass sconvolve

echo


#--- print results and set exit code

if [ $toterr -eq 0 ]; then
    echo "Test completed: $totmod modules successfully tested."
    code=0
else
    echo
    echo "***** $toterr module(s) failed ($totmod tested)."
    echo "Note that some errors may have been caused by dependencies."
    echo "Please fix the modules in the order given below."
    echo
    echo "***** the following modules failed:"
    cat $tmp/failed
    code=1
fi

#--- delete temporary files and dirs
if [ $rmtmproot = 1 ]; then 
    rm -rf $tmproot/
else
    rm -rf $tmp
fi

#--- exit
exit $code
